### ISSUE TITLE
No "Mes de Validade do Cartão", há um bug de estilo quando o mes vem apenas com um caractere [1-9]

### ISSUE THREAD

**Issue by iguoliveira** [DaniHRE/react-pay-card#1]
Utilizando o cartão junto de minha API, estava tudo bem, até que, ao puxar o mes para por na validade, ele veio com apenas um caracter, algo normal, pelo backend gerar os numeros de validade automaticamente.
Porém, ao inserir na props 'cardMonth' do cartão, um bug estético ocorreu:

![image](https://user-images.githubusercontent.com/57506257/203452913-dc694193-1d7a-4327-a54a-f44d8311af2e.png)

Fica este espaço vazio, quebrando a estilização

**Comment by DaniHRE** [comment]
'Issue' fechada, correção de bug feita com sucesso.
Muito Obrigado.
